name: Deploy PDF to GitHub Pages

on:  
  push:
    branches:
      - 'main'
      - 'CI*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload PDF to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/report/output.pdf

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

